name: PR Build and Unit Testing
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
        - "main*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr_build_and_unit_testing:
    name: PR Compilation and Unit Testing
    runs-on: ${{ vars.MACOS_RUNNER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reconfigure git to use HTTP authentication
        run: |
          git config --global url."https://${{ secrets.READ_GH_ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global -l
        
      - name: Notify Status in Slack
        if: ${{ success() || failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_IOS_BOT_TOKEN }}
          PULL_REQUEST_JOB_STATUS_COLOR: ${{ steps.build.outcome == 'success' && '#3BC3A3' || steps.build.outcome != 'success' && '#ed452b' }}
          PULL_REQUEST_BUILD_STATUS: ${{ steps.build.outcome == 'success' && 'BUILD PASSED - Compile check successful' || steps.build.outcome != 'success' && 'Build Failed!' }}
          PULL_REQUEST_UNIT_TESTING_STATUS_COLOR: ${{ steps.unit_testing.outcome == 'success' && '#3BC3A3' || steps.unit_testing.outcome != 'success' && '#ed452b' }}
          PULL_REQUEST_UNIT_TESTING_STATUS: ${{ steps.unit_testing.outcome == 'success' && 'Successful' || steps.unit_testing.outcome != 'success' && 'Failed' }}
          PULL_REQUEST_LOGS_URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          PULL_REQUEST_COMMIT_URL: ${{ github.event.pull_request.head.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }}
        with:
          channel-id: "${{ vars.SLACK_DEV_CHANNEL_ID }}"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ env.PULL_REQUEST_BUILD_STATUS }}*"
                  }
                }
              ],
              "attachments": [
                {
                  "color": "${{ env.PULL_REQUEST_JOB_STATUS_COLOR }}",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*App:*\nsmartcast-ios"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Branch:*\n${{ github.event.pull_request.head.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow Action:*\n${{ github.workflow }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author:*\n${{ github.event.pull_request.user.login }}"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Change Log:*\n${{ github.event.pull_request.title }}"
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "color": "${{ env.PULL_REQUEST_UNIT_TESTING_STATUS_COLOR }}",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Unit Testing:* ${{ env.PULL_REQUEST_UNIT_TESTING_STATUS }}"
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Logs"
                      },
                      "url": "${{ env.PULL_REQUEST_LOGS_URL }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Commit"
                      },
                      "url": "${{ env.PULL_REQUEST_COMMIT_URL }}"
                    }
                  ]
                }
              ]
            }
        continue-on-error: true

  pr_swift_linting:
    name: Swiftlint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
